# Direct restore from external storage (S3 via rclone)
# Requires guest helper to have rclone configured with the named remote
apiVersion: filerestore.kubevirt.io/v1alpha1
kind: VirtualMachineFileRestore
metadata:
  labels:
    app.kubernetes.io/name: vm-file-restore-operator
    app.kubernetes.io/managed-by: kustomize
  name: restore-from-remote-sample
  namespace: default
spec:
  target:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: fedora
  source:
    remote:
      name: s3_backup
      bucket: buck1
  sourcePath: /home/donald
